#!/usr/bin/env sh
echo "Running commit msg hooks (Conventional commit)..."

if [ -f "pnpm-lock.yaml" ]; then
  PM="pnpm"
elif [ -f "yarn.lock" ]; then
  PM="yarn"
elif [ -f "bun.lockb" ] || [ -f "bun.lock" ]; then
  PM="bun"
else
  PM="npm"
fi

if [ "$PM" = "npm" ]; then
  npx --no-install commitlint --edit "$1"

elif [ "$PM" = "bun" ]; then
  bunx --no-install commitlint --edit "$1"

else
  $PM dlx --no-install commitlint --edit "$1"
fi

echo "Done."